version: "3"
services:
  flask-app:
    build: 
      dockerfile: containers/flask/Dockerfile
      context: .
    ports:
      - 5000
    volumes:
      - ./:/app
      - ./public:/app/public

  flask-nginx:
    image: nginx
    volumes:
      - ./containers/nginx/proxy.conf:/etc/nginx/conf.d/default.conf
      - ./public:/app/public
    ports:
      - 80:80
